softwareone-platform/swo-adobe-vipm-extension

adobe_vipm/adobe/client.py
adobe_vipm/adobe/utils.py
adobe_vipm/flows/constants.py
adobe_vipm/flows/fulfillment.py
adobe_vipm/flows/mpt.py
adobe_vipm/flows/shared.py
adobe_vipm/flows/utils.py
swo/mpt/extensions/runtime/commands/run.py
swo/mpt/extensions/runtime/djapp/management/commands/consume_events.py
swo/mpt/extensions/runtime/events/producers.py
swo/mpt/extensions/runtime/initializer.py
swo/mpt/extensions/runtime/master.py
swo/mpt/extensions/runtime/swoext.py
swo/mpt/extensions/runtime/workers.py
tests/adobe/test_client.py
tests/conftest.py
tests/flows/fulfillment/test_change.py
tests/flows/fulfillment/test_purchase.py
tests/flows/fulfillment/test_termination.py
tests/flows/test_errors.py
tests/flows/test_mpt.py
tests/flows/test_shared.py

- enums are lowercase (Change -> change)
- adjust order/subscription/agreement items structure (items -> lines)
- use externalId for parameters referencing
- order --> ordering
- structured parameter values are passed by json strings

219737 Adjust API and data structures with existing state of MPT API

---

adobe_vipm/adobe/client.py
adobe_vipm/adobe/config.py
adobe_vipm/adobe/utils.py
adobe_vipm/extension.py
adobe_vipm/flows/constants.py
adobe_vipm/flows/errors.py
adobe_vipm/flows/fulfillment.py
adobe_vipm/flows/shared.py
adobe_vipm/flows/utils.py
adobe_vipm/flows/validation.py
adobe_vipm/models.py
devmock/endpoints.py
devmock/mockgendata.py
docker-compose.yml
poetry.lock
pyproject.toml
swo/mpt/extensions/runtime/djapp/conf/default.py
tests/adobe/test_client.py
tests/conftest.py
tests/django/settings.py
tests/flows/fulfillment/test_change.py
tests/flows/fulfillment/test_purchase.py
tests/flows/fulfillment/test_termination.py
tests/flows/test_shared.py
tests/flows/test_validation.py
tests/test_extension.py

* company profile and contact validation
* change to structured param error
* change to structured phone

219744 company profile and contact validation

---

README.md
docker-compose.yml

Add configuration description and instruction on how to run against devmock

Update README.md, add configuration description

---

.github/workflows/pr-build-merge.yml
adobe_vipm/flows/validation/change.py
tests/flows/validation/test_change.py

… last two weeks before renewal

[HF] MPT-4961 returnable orders are not ignored when downsizing within the last two weeks before renewal

---

adobe_vipm/flows/global_customer.py
tests/flows/test_global_customer.py

(cherry picked from commit a4d96d4158030d8279ed8f38e80df8c7f8963e5a)

[HF] MPT-6502 Enable deployment subscriptions auto-renew

---

tests/conftest.py
tests/core/test_core_registry.py
tests/core/test_core_utils.py
tests/runtime/commands/test-cli.py
tests/runtime/events/test_events_dispatcher.py
tests/runtime/events/test_events_producers.py
tests/runtime/test_runtime_initializer.py
tests/runtime/test_runtime_logging.py
tests/runtime/test_runtime_master.py
tests/runtime/test_runtime_utils.py
tests/runtime/test_runtime_workers.py

This part of swo-adobe-vipm-extension isn’t covered by tests. https://github.com/softwareone-platform/swo-adobe-vipm-extension/tree/main/swo/mpt
https://softwareone.atlassian.net/browse/MPT-4225

[MPT-4225] Cover swo mpt runtime with tests

---

adobe_vipm/flows/constants.py
adobe_vipm/flows/fulfillment/change.py
adobe_vipm/flows/utils.py
adobe_vipm/flows/validation/change.py
tests/flows/fulfillment/test_change.py

…returnable orders when they should just set renewal quantity
(cherry picked from commit 98afe400e9ee0490e546a6cd45b783872ed20766)

[HF] MPT-7003 downsizes within the last two weeks before renewal look for returnable orders when they should just set renewal bp

---

adobe_vipm/flows/sync.py
adobe_vipm/flows/utils.py
tests/flows/test_sync.py

MPT-6970 Sync 3YC parameters from Deployment agreements from main agreement back to GC agreement

---

.github/workflows/pr-build-merge.yml

Possible fix for pr_build_merge syntax error on github action
https://softwareone.atlassian.net/browse/MPT-8391

[MPT-8391] Possible fix for pr_build_merge syntax error on github action

---

.gitignore
adobe_vipm/flows/utils.py
adobe_vipm/flows/validation/base.py

Fix some typos and arguments in the docstring

Fix some typos and arguments in the docstring

---

adobe_vipm/flows/validation/transfer.py
tests/flows/validation/test_transfer.py

Fix for https://softwareone.atlassian.net/browse/MPT-8676
I commented in a few places in the review to clarify the decisions behind the implementation of the fix.
I've been forced by SonarQube to do a refactoring. Since I'm very new, I played it safe and just mainly broke down the function I fixed into helper functions. Please let me know if I should continue working on this and deliver a better refactoring, but it will require understanding the business logic.

[MPT-8676] "Value has to be a non empty array." for GET /catalog/items?in(externalIds.vendor,()) in transfer validation

---

adobe_vipm/flows/constants.py
adobe_vipm/flows/validation/transfer.py
tests/flows/validation/test_transfer.py

MPT-7834 refactor the validate function

MPT-7834 Migrating three year committed produced empty items

---

adobe_vipm/flows/fulfillment/shared.py
adobe_vipm/flows/global_customer.py
adobe_vipm/flows/migration.py
tests/conftest.py
tests/flows/fulfillment/test_transfer.py
tests/flows/test_global_customer.py
tests/flows/test_migration.py

Fix for keyerror on address in companyProfile
KeyError: 'address'  while accessing Adobe Customer
https://softwareone.atlassian.net/browse/MPT-10230

[MPT-10230] Fix for keyerror on address in companyProfile

---

adobe_vipm/flows/fulfillment/shared.py
adobe_vipm/flows/global_customer.py
adobe_vipm/flows/utils.py
tests/flows/fulfillment/test_transfer.py

Created helper function for setting profile address
Added TODO to refactor some tests later with fixtures.
https://softwareone.atlassian.net/browse/MPT-10230

[MPT-10230] Created helper function for setting profile address

---

adobe_vipm/adobe/constants.py
adobe_vipm/flows/sync.py
adobe_vipm/management/commands/sync_3yc_enrollments.py
pyproject.toml
tests/commands/test_sync_3yc_enrollments.py
tests/conftest.py
tests/flows/test_sync.py
uv.lock

While working on this ticket I realised that `process_3yc` command is checking for a different parameter that the one specified by Agreement Sync Improvements BDR. Also, the synchronisation operation describe in BDR related to this ticket asks for running every 5 minutes while `process_3yc` much less frequently.  Taking the above under consideration, I decided to create a new Django command specifically for this ticket.

MPT-11073 Update Sync Agreement triggering conditions based on 3YCEnrollStatus

---

adobe_vipm/airtable/models.py
adobe_vipm/flows/sync.py
tests/conftest.py
tests/flows/test_sync.py

Changes based on comment in https://softwareone.atlassian.net/browse/MPT-11087

MPT-11087 remove end-of-sale SKU logic and related tests

---

tests/flows/fulfillment/test_shared.py
tests/flows/fulfillment/test_transfer.py
tests/flows/test_benefits.py
tests/flows/test_sync.py
tests/flows/validation/test_transfer.py

Small refactor replacing the mpt_client mock with the mock_mpt_client fixture

MPT-12622: use mock-mpt-client fixture

---

tests/adobe/test_client.py
tests/conftest.py
tests/flows/fulfillment/test_purchase.py
tests/flows/fulfillment/test_reseller_change.py
tests/flows/fulfillment/test_shared.py
tests/flows/test_helpers.py
tests/flows/test_utils.py
tests/flows/validation/test_purchase.py
tests/flows/validation/test_shared.py
tests/flows/validation/test_termination.py
tests/flows/validation/test_transfer.py
tests/test_extension.py

* Replaced order fixture with mock_order 
* Replaced simple order creation with the mock_order fixture
* Replaced some mocked_client with the mock_mpt_client fixture

MPT-12622: use mock-order fixture

---

adobe_vipm/extension.py
adobe_vipm/flows/errors.py
adobe_vipm/flows/fulfillment/base.py
adobe_vipm/flows/fulfillment/change.py
adobe_vipm/flows/fulfillment/configuration.py
adobe_vipm/flows/fulfillment/purchase.py
adobe_vipm/flows/fulfillment/shared.py
adobe_vipm/flows/fulfillment/termination.py
adobe_vipm/flows/fulfillment/transfer.py
adobe_vipm/flows/global_customer.py
adobe_vipm/flows/migration.py
adobe_vipm/flows/sync.py
adobe_vipm/flows/utils/customer.py
adobe_vipm/flows/utils/parameter.py
adobe_vipm/flows/utils/subscription.py
adobe_vipm/flows/validation/change.py
adobe_vipm/flows/validation/shared.py
adobe_vipm/flows/validation/transfer.py
adobe_vipm/management/commands/create_resellers.py
setup.cfg
tests/test_apps.py

Remove [WPS111](https://wemake-python-styleguide.readthedocs.io/en/stable/pages/usage/violations/naming.html#wemake_python_styleguide.violations.naming.TooShortNameViolation) code from per-file-ignores

MPT-12622: remove WPS111 code from ignore

---

adobe_vipm/adobe/mixins/subscription.py
adobe_vipm/flows/utils/deployment.py
adobe_vipm/flows/utils/parameter.py
adobe_vipm/management/commands/migrate_mpt_assets.py
tests/adobe/mixins/test_subscription.py
tests/conftest.py
tests/management/commands/test_migrate_mpt_assets.py

Add a command to update the Assets already created during the release of Assets to production

MPT-12389: add migrate mpt assets command
